#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers


#=================================================
# INSTALLATION
#=================================================

hostname=$(hostname)
rpc_key=$(ynh_app_setting_get reticulum --key=rpc_key)

pushd $install_dir
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_exec_as_app "$install_dir/venv/bin/pip" install nomadnet

    mkdir -p "$install_dir/.nomadnetwork"
    chown "$app:$app" "$install_dir/.nomadnetwork"
    ynh_config_add --jinja --template=config.j2 --destination="$install_dir/.nomadnetwork/config"

    mkdir -p "$install_dir/.reticulum"
    chown "$app:$app" "$install_dir/.reticulum"
    ynh_config_add --jinja --template=reticulum_config.j2 --destination="$install_dir/.reticulum/config"

    ynh_config_add --template=wrapper --destination="$install_dir/nomadnet_ynh"
    chmod +x "$install_dir/nomadnet_ynh"


popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
