#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers


#=================================================
# INSTALLATION
#=================================================

pushd $install_dir
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_exec_as_app "$install_dir/venv/bin/pip" install nomadnet
    mkdir -p "$install_dir/.nomadnetwork"
    chown "$app:$app" "$install_dir/.nomadnetwork"
    ynh_config_add --jinja --template=config.j2 --destination="$install_dir/.nomadnetwork/config"
    ynh_config_add --template=wrapper --destination="$install_dir/nomadnet_ynh"

popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
