#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
chown -R "$app:$app" "$install_dir"

#=================================================
# RESTORE THE APP DATA DIR
#=================================================
ynh_script_progression "Restoring the app data directory..."

ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
