#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# UPGRADE
#=================================================

pushd $install_dir
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade nomadnet
popd


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"

