#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# UPGRADE
#=================================================

pushd $install_dir
    python3 -m venv $install_dir/venv
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings $install_dir/venv/bin/pip install --upgrade pip
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade nomadnet==$(ynh_app_upstream_version)
popd


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"

